### ISSUE TITLE
SQLException Cannot create data при получении данных из БД

### ISSUE THREAD

**Issue by KattyKukh** [KattyKukh/Marracash#12]
## Описание
При исполнении запроса к базе данных на получение строки вида "SELECT * FROM credit_request_entity ORDER BY created DESC LIMIT 1" получаю SQLException Cannot create data.

## Шаги воспроизведения
1. Запустить контейнеры MySQL, PostgreSQL и симулятора платежей (docker-compose.yml) для создания тестового окружения.
2. Запустить приложение aqa-shop.jar
3. Запустить тест successAddedCreditInDBIfApprovedCard(). 

*Ожидаемый результат:* тест падает на строке Assertions.assertEquals(rowCreditTable.getBank_id(), rowOrderTable.getCredit_id()); т.к. в таблице order_entity id кредитной транзации не записывается в столбец credit_id.  

*Фактический результат:* Тест падает на строке  Assertions.assertEquals(statusCard, rowCreditTable.getStatus()); с исключением SQLException Cannot create data.

## Скриншот
![ошибка запроса к БД](https://user-images.githubusercontent.com/103628827/207583968-768385d3-d54b-4256-9bdc-679d394018c9.png)

## Окружение
* **Операционная система:** Linux Ubuntu 20.04
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **JAVA:** OpenJDK 11

**Comment by ArRomanov** [comment]
1. Над вложенными классами моделями таблиц БД вместо аннотации Value добавьте эти аннотации
```
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
```
2. Вынесите каждую из этих моделей в отдельные классы
3. При использовании аннотации SneakyThrows конструкцию try-catch не нужно использовать, можно полностью убрать из всех методоы

1 пункт решает конкретно вашу проблему, 2 и 3 просто улучшения, о которых я бы написал в ревью потом
